topics:
- name    : recover
  topic   : recover/cmd_vel
  timeout : 0.5
  priority: 100
- name    : move_base
  topic   : move_base_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 1
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 100

